### ISSUE TITLE
Bake Spectrograms (windows)

### ISSUE THREAD

**Issue by rndsum** [example-sk/audvis#3]
Trying to run Bake Spectrograms on windows causes blender to crash after when selecting a path.

If you do not select a path
![image](https://user-images.githubusercontent.com/59740457/184674018-9543e168-a542-4fd9-8cf1-d9d5a5d8bc33.png)
this error message is generated.

**Comment by example-sk** [comment]
Oh, spectrogram baking is in horrible state now. I will try to remake it into subpanel instead of modal window.

**Comment by example-sk** [comment]
Can you check if it works now, pls? The change is only in git for now, I don't want to release it before testing.
