### ISSUE TITLE
Real Time Analyizer only lists Microphones, no sound output of OS

### ISSUE THREAD

**Issue by TrackLab** [example-sk/audvis#4]
Hey. I just found this addon, and it would do exactly what I need. Unfortunately, it only lists Microphones as Input devices, which work. But it lists no Windows output, so I cant test it on live music..

**Comment by TrackLab** [comment]
Note, there is one Headphone option, but when I select that it says "Error opening InputStream: Invalid number of channels [PaErrorCode -9998]

**Comment by example-sk** [comment]
Do you have Stereo Mix correctly configured? It's needed in Windows.

**Comment by TrackLab** [comment]
> Do you have Stereo Mix correctly configured? It's needed in Windows.

How do you mean? My microphones and audios are all normally set up in Windows.

**Comment by example-sk** [comment]
Please watch this https://www.youtube.com/watch?v=Bd3moKLV5sE

If it doesn't help, write into google "Stereo Mix" and try another solutions.
