### ISSUE TITLE
crash with blender 3.6.5

### ISSUE THREAD

**Issue by fgiering** [example-sk/audvis#5]
### Steps to reproduce:

1. create blender project with wav-file in sequencer
2. activate audvis
3. activate sequence analyzer
4. load .wav-File in sequence anlyzer
5. save projekt
6. close blender
7. move wav-File in explorer
8. open blender
9. load projekt
10. hit "play"

### Expected result:
Displays error-message: "File: xyz.wav is not reachable. Go to 'Outliner' > 'Data API' and check filepath"

### Actual result:
blender crashes

I checked with deactivated audvis plugin. Blender doesn't show an error for the file neither. But doesn't crashes and is still working and playing.

**Comment by example-sk** [comment]
Thanks for reporting. The fix will be ready soon.

**Comment by example-sk** [comment]
Fix released right now
https://github.com/example-sk/audvis/releases/tag/4.7.2
