### ISSUE TITLE
Real Time Analyzer Setup Script not Working in Blender 4.0.1

### ISSUE THREAD

**Issue by INTOODEEP-dev** [example-sk/audvis#6]
When I do the (re)install python packages in blender 4.0.1 I get this result: 

> Python: Traceback (most recent call last):
>   File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\audvis\ui\install_ui\all.py", line 12, in execute
>     install_lib.PipInstaller().install()
>   File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\audvis\ui\install_lib.py", line 121, in install
>     self._open_window()
>   File "C:\Users\Brandon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\audvis\ui\install_lib.py", line 116, in _open_window
>     bpy.ops.screen.screen_full_area(override)
>   File "C:\Blender\blender-4.0.1-windows-x64\blender-4.0.1-windows-x64\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
>     C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
>   File "C:\Blender\blender-4.0.1-windows-x64\blender-4.0.1-windows-x64\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
>     raise ValueError("1-2 args execution context is supported")
> ValueError: 1-2 args execution context is supported
> 

After playing around and not getting anywhere with it, I downloaded 3.6.5 LTS and tried it, and it worked fine for me on there, so seems to be an issue specific to the new blender version I think.

**Comment by example-sk** [comment]
Sorry, I have already [fixed this bug](https://github.com/example-sk/audvis/commit/22bcec35ed98fa9c876b0637844052394babede6), but I forgot to release the fix. It will be released soon.

**Comment by example-sk** [comment]
Fix released right now
https://github.com/example-sk/audvis/releases/tag/4.7.2
