### ISSUE TITLE
Entering Party mode crashes Blender

### ISSUE THREAD

**Issue by mertakbal** [example-sk/audvis#7]
entering partymode crashes Blender, with or without any selected modes.
OS : Ubuntu 22
Blender version : 4.0.2

# Blender 4.0.2, Commit date: 2023-12-05 07:41, Hash 9be62e85b727
Python: Traceback (most recent call last):
  File "/home/mrt/.config/blender/4.0/scripts/addons/audvis/ui/partymode/__init__.py", line 21, in invoke
    return in_window.invoke(self, context, event)
  File "/home/mrt/.config/blender/4.0/scripts/addons/audvis/ui/partymode/in_window.py", line 31, in invoke
    bpy.ops.screen.screen_full_area({
  File "/snap/blender/4300/4.0/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "/snap/blender/4300/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported  # Error

# backtrace
/snap/blender/4300/blender() [0xf3a7b0]
/snap/blender/4300/blender() [0x8c42ec]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f2e8ea42520]
/snap/blender/4300/blender() [0xf53123]
/snap/blender/4300/blender() [0xf54b69]
/snap/blender/4300/blender() [0xf551dd]
/snap/blender/4300/blender() [0xf55cb3]
/snap/blender/4300/blender() [0xf48840]
/snap/blender/4300/blender() [0x72521b]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f2e8ea29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f2e8ea29e40]
/snap/blender/4300/blender() [0x8c022e]

# Python backtrace

**Comment by example-sk** [comment]
Thanks for reporting this bug.

AudVis 4.7.3 fixes this issue.

**Comment by mertakbal** [comment]
Dear, example-sk,
Thank you so much for fixing the bug.
Also Audvis is a great tool! I use it in my own work as well as in my
teaching at the university.
I already bought it two years ago as you were still selling it in
blendermarket before publishing for free.
I would like to tag you in my posts with works on Instagram and YouTube to
promote audvis. Like this animation
https://www.instagram.com/reel/C1aVtBFAsqu/?igsh=dDlmeWw1NjNkODJ2


Can you please tell me which hashtags or mentions are the best for you?

All the best and thanks again
My las
